### PR TITLE
add openjdk11 and openjdk14 for travis-ci scripts.

### PR DESCRIPTION
**Pull request by XenoAmess**
as title.

### CODE REVIEW

**Comment by XenoAmess** [comment]
> No objection from me, though someone needs to investigate the build errors (I think even jdk8 failed). Happy if it's merged as-is, or if we wait until the tests are fixed, then rebase/merge.
> 
> Thanks @XenoAmess !
> 
> Bruno

Hi.
This build error is not my fault.
I have no interest in investigating the real reason / fix it, but I checked this repo can NEVER pass all of its junit tests since commit 967b9bed79f51040597d68ef98512a24b0e94e41m  .

The details are in commons-dev mailing list's mail : `[commons-graph] branch master updated: Travis CI configuration.`
As I said in mailing list, I'm really curious. I'll quote the key part of my opinion below.

> Btw: I tested (if my memory are correct, as I didn't make a log for it) the latest commit (fail) , the first commit at year 2012(fail), the first commit of the repo(pass), the first commit of year2011month10(fail), the first commit of year2011month7(fail), and I tried every version from year2011month7 back, and finally I get the last commit that can pass all junit tests be 967b9bed79f51040597d68ef98512a24b0e94e41m ,which is just 3 hours after the repo created.
> 
> Btw2: Is it a usual thing in commons, for a repo's branch master can never pass its own junit tests for years? I'm new here, knowing nearly nothing about commons, and become very confused.
> Btw3: And do the users of this repo know about this?

**Comment by ameyjadiye** [comment]
> @kinow
> 
> > No objection from me, though someone needs to investigate the build errors (I think even jdk8 failed). Happy if it's merged as-is, or if we wait until the tests are fixed, then rebase/merge.
> > Thanks @XenoAmess !
> > Bruno
> 
> Hi.
> This build error is not my fault.
> I have no interest in investigating the real reason / fix it, but I checked this repo can NEVER pass all of its junit tests since commit 967b9bed79f51040597d68ef98512a24b0e94e41m .
> 
> The details are in commons-dev mailing list's mail : `[commons-graph] branch master updated: Travis CI configuration.`
> As I said in mailing list, I'm really confused & curious. I'll quote the key part of my opinion below.
> 
> > Btw: I tested (if my memory are correct, as I didn't make a log for it) the latest commit (fail) , the first commit at year 2012(fail), the first commit of the repo(pass), the first commit of year2011month10(fail), the first commit of year2011month7(fail), and I tried every version from year2011month7 back, and finally I get the last commit that can pass all junit tests be 967b9bed79f51040597d68ef98512a24b0e94e41m ,which is just 3 hours after the repo created.
> > Btw2: Is it a usual thing in commons, for a repo's branch master can never pass its own junit tests for years? I'm new here, knowing nearly nothing about commons, and become very confused.
> > Btw3: And do the users of this repo know about this?

Build is not failing here, rather its Travis checks. we should remove ```checkstyle:check``` for now to eliminate delima of what's actually failing.

**Comment by XenoAmess** [comment]
Hi.
> Build is not failing here, rather its Travis checks. 

You mean the travis-ci failure can influence my local tests?

Besides. I've already pointed out where it fails in mailing list for you if my memory is correct.

```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TarjanTestCase.verifyHasStronglyConnectedComponents:145 expected:<[[{ A }, { B }, { D }], [{ E }, { F }], [{ C }, { G }, { H }]]> but was:<[[{ H }, { G }, { C }, { E }, { F }, { D }, { B }, { A }]]>
[ERROR]   KruskalTestCase.testP4UniformWeightsMinimumSpanningTree:276 expected:<{{ A }=[{ B }], { B }=[{ A }, { C }], { C }=[{ B }, { D }], { D }=[{ C }]}> but was:<{{ A }=[{ B }], { B }=[{ A }], { C }=[{ D }], { D }=[{ C }]}>
[ERROR] Errors: 
[ERROR]   GraphColoringTestCase.testSudoku:193 » NotEnoughColors Input color set [0, 1, ...
[INFO] 
[ERROR] Tests run: 160, Failures: 2, Errors: 1, Skipped: 1
```

And I am not a person who will lie on this kind of thing. 
I said the repo can never pass all of its unit tests since 967b9bed79f51040597d68ef98512a24b0e94e41m , and that is exactly what happened.

This is not ci's fault.

**Comment by kinow** [comment]
Didn't say this was breaking the build @XenoAmess , @ameyjadiye , just that eventually someone needs to fix it (I've approved it already, so I'm +1 for merging it).

I simply mentioned the option to merge as-is, or wait until the build is first fixed (I didn't look what was broken, thanks for pointing that it might be checkstyle @ameyjadiye , that may be easier to fix/disable). And that's in case another committer prefer to defer the merge :+1:

**Comment by XenoAmess** [comment]
And I don't know why this repo can run like this.
Do we REALLY run all junit tests and make them pass before every commits merged into branch master?

**Comment by kinow** [comment]
> And I don't know why this repo can run like this.
> Do we REALLY run all junit tests and make them pass before every commits merged into branch master?

We try @XenoAmess . Some times a build may fail because of a glitch in CI (e.g. failed to clone a repo), or because of a dependency that was updated somewhere, or because of a flaky test.

Some times a broken pull request slips in, and we need to fix it later. But, IMHO, if you have other thoughts on how it should run, I think the best place to discuss is probably the mailing list.

I was just looking at the pending pull requests of [graph] to see if I could help reviewing. I'm with limited bandwidth to volunteer on ASF, so not the best person to really give my opinion here :+1:

**Comment by XenoAmess** [comment]
@kinow 

> Some times a broken pull request slips in, and we need to fix it later. 

This is not the exact situation here.
The exact situation here is: tons of (at least 100+) commits slips in, and nobody fixed it later. 
967b9bed79f51040597d68ef98512a24b0e94e41m  is just 3 hours after the repo started at, year 2012month6day11, means through all the life of this repo, the only moment it can pass all of unit tests is **3 hours**.

> I think the best place to discuss is probably the mailing list

Well I think so, as this is not a so good thing for everybody to see.
But you can notice that I asked the original 3 questions on mailing list first.
If I can get enough responce from mailing list, I will never ask again on github.

**Comment by kinow** [comment]
The test `UniVsBiDijkstraBenchmarkTestCase#performUnidirectionalDijkstra` took longer than the maximum threshold, and caused the build for Java 11 to fail. Will keep an eye on this test, and if it keeps failing, will simply increase that threshold (at this time, I don't think that should be a problem, as it hasn't yet reached a full release, we'll have time to fine-tune algorithms as needed later).

Merging, thanks and sorry for the delay @XenoAmess !

Bruno

**Pull request merged**
